// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8exZWcQNEqLqN_r3VorMs_AGgBiBwNw',
    appId: '1:735904849421:web:407aff55b668af20893f44',
    messagingSenderId: '735904849421',
    projectId: 'fir-tutorial-53afc',
    authDomain: 'fir-tutorial-53afc.firebaseapp.com',
    storageBucket: 'fir-tutorial-53afc.firebasestorage.app',
    measurementId: 'G-1Z0857YD6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaRgqp3_ilTyqBwbckxeijxtjGK8apWY',
    appId: '1:735904849421:android:ca40e5b6f97dbeb3893f44',
    messagingSenderId: '735904849421',
    projectId: 'fir-tutorial-53afc',
    storageBucket: 'fir-tutorial-53afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc565BjUypMj3i4K7KbwLStGp9gTcZ7Bo',
    appId: '1:735904849421:ios:f427eb46b8daca51893f44',
    messagingSenderId: '735904849421',
    projectId: 'fir-tutorial-53afc',
    storageBucket: 'fir-tutorial-53afc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc565BjUypMj3i4K7KbwLStGp9gTcZ7Bo',
    appId: '1:735904849421:ios:f427eb46b8daca51893f44',
    messagingSenderId: '735904849421',
    projectId: 'fir-tutorial-53afc',
    storageBucket: 'fir-tutorial-53afc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj8exZWcQNEqLqN_r3VorMs_AGgBiBwNw',
    appId: '1:735904849421:web:b6f8c4c4e49d2475893f44',
    messagingSenderId: '735904849421',
    projectId: 'fir-tutorial-53afc',
    authDomain: 'fir-tutorial-53afc.firebaseapp.com',
    storageBucket: 'fir-tutorial-53afc.firebasestorage.app',
    measurementId: 'G-HQTV12RYJT',
  );
}
